name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Get package name and version
        id: get_pkg_info
        run: |
          echo "#----------------------------------------------"
          echo "pwd: $(pwd)"
          ls -lah
          echo "#----------------------------------------------"
          echo "version: $(jq -r .version package.json)"
          echo "PACKAGE_NAME=$(jq -r .name package.json)" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Use package name and version in subsequent steps
        run: |
          echo "Package name: $PACKAGE_NAME"
          echo "Version: $PACKAGE_VERSION"

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Extract Release Version from CHANGELOG.md
        id: extract_version
        run: |
          # Adjust the following command to match how version info is formatted in CHANGELOG.md
          NEXT_VERSION=$(grep -oP '^## \[\K[^\]]+' CHANGELOG.md | head -n 1)
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Update package.json version
        run: |
          if [ -n "$NEXT_VERSION" ]; then
            npm version $NEXT_VERSION --no-git-tag-version
          else
            echo "No version found to update"
          fi

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # git add CHANGELOG.md
          git add .
          git commit -m "chore(release): $NEXT_VERSION" || echo "No changes to commit"
          git push origin ${{ github.ref_name }}  # This uses the target branch from the on event
