name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Get package name and version
        id: get_pkg_info
        run: |
          echo "#----------------------------------------------"
          echo "pwd: $(pwd)"
          ls -lah
          echo "#----------------------------------------------"
          echo "version: $(jq -r .version package.json)"
          echo "PACKAGE_NAME=$(jq -r .name package.json)" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Use package name and version in subsequent steps
        run: |
          echo "Package name: $PACKAGE_NAME"
          echo "Version: $PACKAGE_VERSION"

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Commit changes
        id: commit_changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore(release): ${PACKAGE_VERSION} [skip ci]\n\nGenerated by Semantic Release"
          git push origin HEAD:release-branch

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Release ${{ steps.get_pkg_info.outputs.version }}"
          body: "Automated release triggered by Semantic Release."
          base: main
          head: release-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Pull Request URL
        id: get_pr_url
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `release-branch`,
              state: 'open',
            });
            const prData = pr.data.find(pr => pr.base.ref === 'main');
            if (prData) {
              console.log(`PR URL: ${prData.html_url}`);
              return prData.html_url;
            } else {
              throw new Error('Pull request not found');
            }
          result-encoding: string
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve Pull Request
        if: steps.get_pr_url.outputs.result != ''
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ steps.get_pr_url.outputs.result }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        if: steps.get_pr_url.outputs.result != ''
        run: gh pr merge "$PR_URL" --merge
        env:
          PR_URL: ${{ steps.get_pr_url.outputs.result }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
