name: Node.js CI

on:
  push:
    branches:
      - main
      - dev
      - stg

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.8.0"

      - name: Get package name and version
        id: get_pkg_info
        run: |
          echo "#----------------------------------------------"
          echo "pwd: $(pwd)"
          ls -lah
          echo "#----------------------------------------------"
          echo "version: $(jq -r .version package.json)"
          echo "PACKAGE_NAME=$(jq -r .name package.json)" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Determine release branch
        id: determine_branch
        run: |
          # Extract the branch name from the GITHUB_REF
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Branch: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Use package name and version in subsequent steps
        run: |
          echo "Package name: $PACKAGE_NAME"
          echo "Version: $PACKAGE_VERSION"

      - name: Install dependencies
        run: npm ci

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Commit changes
        id: commit_changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore(release): ${PACKAGE_VERSION} [skip ci]\n\nGenerated by Semantic Release"
          git push origin HEAD:${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Release ${{ steps.get_pkg_info.outputs.version }}"
          body: "Automated release triggered by Semantic Release."
          base: main
          head: ${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve Pull Request
        if: steps.create_pr.outputs.pull-request-url != ''
        run: gh pr review --approve ${{ steps.create_pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        if: steps.create_pr.outputs.pull-request-url != ''
        run: gh pr merge ${{ steps.create_pr.outputs.pull-request-url }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
